### PR TITLE
Update readme with links to doc and added images to repo.

### PR DESCRIPTION
**Pull request by dnth**

### CODE REVIEW

**Comment by dnth** [comment]
@amirmk89 I've added your suggestions. Please review them and let me know if you see other issues.

**Comment by dbickson** [comment]
@dnth nice design !!
A couple of small ones:
1) can you add also docker as one of the platforms, we have docker https://hub.docker.com/repository/docker/karpadoni/fastdup-ubuntu-20.04/general
2) In users that liked fastdup, need to add that Suhail is ex-CEO Mixpanel and now CEO Playground.ai.
3) Will it also be possible to add Eric Wallace from Berkeley , has a popular paper about copyright infridgement of generative models
Screen Shot 2023-02-01 at 17 18 04
You can find both their posts in twitter. Feel free to change the design.

**Review by amiralush — APPROVED** [review]

**Comment by dnth** [comment]
@dbickson the tweet from Eric Wallace was removed from @amiralush previous suggestion. Do we want to re-include the tweet?

**Comment by dbickson** [comment]
@dnth I agreed now with @amiralush on the following:
can you please make an animated gif with 3 quotes that are changing:
1) Suhail Doshi, ex-CEO mixpanel and CEO Playground.ai, "fastdup worked great. Already on my way".
2) Eric Wallace, PhD student @ Berkeley, author of the popular paper about copyright violation of generative models: "Everyone should de-duplicate their data. I found fastdup to work pretty well".
3) Srinivasa Rao Jami, Senior Manager Data Science @ Meesho, largest online Indian retailer: "fastdup significantly helps us improve the  quality of our 200,000,000 products gallery"

**Comment by dnth** [comment]
@dbickson I've included your suggestions. Would you please review the PR?

**Review by amirmk89 — APPROVED** [review]

**Comment by dbickson** [comment]
@dnth thanks for adding user quotes, now please remove the detailed boxes for suhail and eric wallace they are no longer needed once we have the summary.

**Pull request merged**
