### PR TITLE
Update image search notebook

### PR DESCRIPTION
**Pull request by dnth**
This PR updates the image search notebook to make it more concise. Removed `matplotlib` installation and dependency in the notebook.

### CODE REVIEW

**Comment by dnth** [comment]
@dbickson would you please review the updated search notebook? Is there anything left to add?

**Comment by dnth** [comment]
Here's the notebook on nbviewer

https://nbviewer.org/github/dnth/fastdup/blob/57fe1b6789423f15ab1e23a111eb4e6b0825ae01/examples/image-search.ipynb

**Comment by amiralush** [comment]
@dnth do you still want this?

**Comment by dnth** [comment]
@amiralush no need for this. I'm closing it now.

**Pull request closed without merging**
